import type { Metadata } from "next";

// These styles apply to every route in the application
import "../styles/globals.css";

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main className="max-w-screen-sm text-slate-100">{children}</main>;
}
